{ lib }: {
  username = "lin";
  userfullname = "Lin Vieira";
  useremail = "lin@fnxln.com";
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....HbV/C8m6dughOGdV3id.L0$6RE7XHIZAPFgNvtZQg6QkZH1G2DLU0i5uIktNVk0u47";
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK8ogpASLrINj4YgzFRfeDxWkvCTTU7cP2U8gPb6P63Z lin@dev-nix"
  ];

}
