{ lib }:
{
  username = "lin";
  userfullname = "Lin Vieira";
  useremail = "lin@fnxln.com";
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../..../s0vgJd8FWp/3jWtwBmtG.$fexmhBo0jCuI.IAB49jR2aBlEv8p8ZSeR.GGIR0CRRA";
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP83jJnv1OMkdj//idC36hi+KG5NKKtG6x/bTmYjOKqS lin@desktop"
  ];

}
