{ lib }:
{
  username = "lin";
  userfullname = "Lin Vieira";
  useremail = "lin@fnxln.com";
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....5cduWEs4AT3DgKpoElf7v0$vFle7ycWZD.6V0ZaSQDE90.6J/aRyjBIzhYmSxPv4/3";
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDF2qZ5KvIRgul0cYEKojtA4COH2lp+CYq/E5qzjtV18 lin@wsl"
  ];

}
